### ISSUE TITLE
It's possible to add MQTT feature ?

### ISSUE THREAD

**Issue by Yoanf26** [borisbu/OctoRelay#163]
Hello,

Sorry for my English, I'm French.

To begin, thank you for this superb plug-in which allows me to partly automate my printer from my computer which is not next to the 3D printer.

But I also have a Home Assistant server. My Raspberry Pi 4b is connected in MQTT, just like OctoPrint and Home Assistant too. So I have a good part of the information that is uploaded to my server.

Sending GCODE commands via MQTT is possible, except to turn on the printer because OctoPrint disables this functionality when the printer is not connected. But I have no status feedback from the relay outputs on the MQTT broker. I looked with MQTT Explorer, I just see it sends GCODE commands.

I know there are scripts, but I wish it was all unified.

So I wanted to know if it is possible to add sending commands and receiving status via MQTT.

**Comment by RobinTail** [comment]
Hello @Yoanf26 ,

Currently the plugin does not support MQTT protocol and I'm not sure at the moment if it's going to have one.

However, the plugin functionality is available via [OctoPrint REST API](https://docs.octoprint.org/en/master/api/).
You could implement your own `MQTT<—>REST API` provider/daemon running on the same Raspberry Pi.

After authenticating (in accordance with the OctoPrint documentation mentioned above),
you can request the plugin function via the following URL:

```
<HOST>/api/plugin/octorelay
```

The payload should be a JSON like this:

```json
{ "pin": "r<INDEX>", "command": "<COMMAND>" }
```

where `COMMAND` is one of: `update, getStatus, listAllStatus`, while `INDEX` is a number from 1 to 8 (not required for `listAllStatus` command).

Thus, you could achieve the desired connectivity already now.

Let me know what you think about it.

In case you will implement such a thing, consider sharing it, so I could estimate a difficulty on integrating similar protocol into the plugin, since I have no experience working with MQTT.

**Comment by RobinTail** [comment]
@Yoanf26 ,

also, you may find insightful the source code of a mobile application that communicates with the plugin via REST API,
check this out:
https://github.com/borisbu/OctoRelay/issues/76

**Comment by Yoanf26** [comment]
Thanks a lot for your answer.

Indeed, after a lot of testing for the command to work under Home Assistant, it works.

I put the code if anyone needs it:

```
#configuration.yaml
binary_sensor:
  - platform: rest
    resource: http://<HOST>/api/plugin/octorelay
    method: POST
    headers:
      Authorization: "Bearer <api_key_octoprint>"
      content-type: "application/json"
    payload: '{ "pin": "r2", "command": "getStatus" }'
    name: Relay Printer 3D
    value_template: "{{value_json.status}}"
    unique_id: relay_printer_3d
    scan_interval: 1
    device_class: running
  - platform: rest
    resource: http://<HOST>/api/plugin/octorelay
    method: POST
    headers:
      Authorization: "Bearer <api_key_octoprint>"
      content-type: "application/json"
    payload: '{ "pin": "r1", "command": "getStatus" }'
    name: Relay LED
    value_template: "{{value_json.status}}"
    unique_id: relay_led
    scan_interval: 1
    device_class: running
  - platform: rest
    resource: http://<HOST>/api/plugin/octorelay
    method: POST
    headers:
      Authorization: "Bearer <api_key_octoprint>"
      content-type: "application/json"
    payload: '{ "pin": "r3", "command": "getStatus" }'
    name: Relay Fan
    value_template: "{{value_json.status}}"
    unique_id: relay_fan
    scan_interval: 1
    device_class: running
  - platform: rest
    resource: http://<HOST>/api/plugin/octorelay
    method: POST
    headers:
      Authorization: "Bearer <api_key_octoprint>"
      content-type: "application/json"
    payload: '{ "pin": "r4", "command": "getStatus" }'
    name: Relay Webcam
    value_template: "{{value_json.status}}"
    unique_id: relay_webcam
    scan_interval: 1
    device_class: running
```


What is unfortunate is that the server sends the 4 commands at regular intervals to retrieve the information.

That's why I found it nice to add this in MQTT because at each change of state, the info is sent to the MQTT broker.
